### ISSUE TITLE
UBUNTU 16.04 support

### ISSUE THREAD

**Issue by maryayi** [mank319/Go-For-It#87] opened 2016-04-23 08:12 UTC
please add support for Ubuntu 16.04 Xenial to your PPA in launchpad

**Comment by mank319** [comment] 2016-04-23 14:42
Thanks for reporting!
I will however close the issue, because it is a duplicate of #86.
(Btw, I just started the build on Launchpad and it said "build successful", so it should be available for installation within the next few hours :wink:)

**Closed by mank319** 2016-04-23 14:42 UTC
