### ISSUE TITLE
[BUG] 'Hamburger' menu non-functional for sorting, in KDE

### ISSUE THREAD

**Issue by RonCam** [mank319/Go-For-It#72] opened 2015-10-26 15:44 UTC
The program's author responded through the 'Go-For-It' blog, saying this was a KDE issue and a bug-report would be in order.  I trust, 'Issues' = 'Bug reports'??  If not, please move to the correct section, many thanks.

**Comment by mank319** [comment] 2015-10-26 15:46
Thank you for reporting this bug, @RonCam. Issues are a collective term for bugs, feature requests and other things, so you posted it in the correct section :wink:

**Comment by RonCam** [comment] 2015-10-26 15:47
Thanks, you are fast!  I was just looking for how to add a 'bug' label, and it 'automagically' appeared.  Thanks again for a great utility program!!

**Comment by mank319** [comment] 2015-10-26 15:53
You'll have to thank Github's email notifications...
Thanks for your nice words regarding the app :smile:

**Comment by RonCam** [comment] 2015-11-17 18:15
I have version 1.4.3.  There's still no ability to manually sort, in KDE ... :-(
Which version do I need, and where do I download it, please?

**Comment by mank319** [comment] 2015-12-11 16:04
Sadly it has not been fixed yet.
I currently do not have KDE set up on any of my machines and my free time is currently very limited to say the least...

**Comment by JMoerman** [comment] 2015-12-12 12:03
@RonCam I can't reproduce this bug on kubuntu 15.10, reordering works just fine here... Can you give some additional information?

A bug I was able to find, however, is that a headerbar is used when running Go for it! in kubuntu 15.10 (KDE 5.4.2).

**Comment by JMoerman** [comment] 2016-11-19 13:48
I'm closing this bug now, because I haven't received any information about this issue in over 11 months. If this issue still occurs feel free to open a new issue.

**Closed by JMoerman** 2016-11-19 13:48 UTC
Labels: bug
