### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by mimf** [mank319/Go-For-It#93] opened 2016-11-17 11:26 UTC
I could not find any info regarding keyboard shortcuts. I tried the obvious ones (ctrl+N to create a new one and so on) but they didn't work. So ya, this is a feature request for keyboard shortcuts:

- Create a new task;
- Delete a task;
- Complete a task;
- Search for a task/project/tag;

**Comment by JMoerman** [comment] 2016-11-17 12:06
Duplicate of #90.

**Closed by JMoerman** 2016-11-17 12:06 UTC
