### ISSUE TITLE
Always on top option missing

### ISSUE THREAD

**Issue by orschiro** [mank319/Go-For-It#59] opened 2015-04-29 12:41 UTC
Dear @mank319,

Why is Go For It missing the "Always on Top" function in the menu that all other applications have?

Example from Chrome:

![image](https://cloud.githubusercontent.com/assets/170947/7391006/b4d50244-ee7d-11e4-8b4b-f45ad3e9b2fd.png)

Example from Go For It:

![image](https://cloud.githubusercontent.com/assets/170947/7391019/d1071772-ee7d-11e4-9160-fdd3c50280ca.png)

Thanks!

Robert

**Comment by rhoconlinux** [comment] 2015-04-29 19:09
Hi! It seems to be an Elementary-only issue (so, gala related stuff) since I don't see this limitation under gnome.  

Check this out:
![Image of goforit](http://i.imgur.com/7MZo0fe.jpg)

**Comment by mank319** [comment] 2015-04-29 19:30
Thanks for testing on Gnome @rhoconlinux. The reason, why this problem does not happen with *Chrome* is because it it does not use client side window decorations (a.k.a. header bars).
I appreciate your report @orschiro, but it is not an issue related to *Go For It!* as such, so I am going to close it, if you don't mind.

I have one glimpse of hope for you though: I am currently thinking about an "always on top, minimalistic floating widget mode" as a nice addition, for those who want to keep an eye on the timer, but don't want it to get in their way. Might take a while to get there though, as there are many other things to fix or implement first :smile:

**Comment by orschiro** [comment] 2015-04-29 20:56
> I have one glimpse of hope for you though: I am currently thinking about an "always on top, minimalistic floating widget mode" as a nice addition

Great to hear that, appreciated! 

> why this problem does not happen with Chrome is because it it does not use client side window decorations (a.k.a. header bars).

So, if I understand correctly, it's a problem directly related to eOS? Are you aware of a related bug report?

**Comment by mank319** [comment] 2015-05-03 10:34
You might want to search *Gala's* bug tracker for more information. Gala is elementary's window manager. I am not aware of a specific existant bug report though.

**Comment by orschiro** [comment] 2015-05-03 15:22
Couldn't find any existing and decided to create one: https://bugs.launchpad.net/elementaryos/+bug/1451206

**Comment by orschiro** [comment] 2015-05-17 05:26
I found an adequate workaround using a shortcut:

![image](https://cloud.githubusercontent.com/assets/170947/7669207/0af8d4b6-fc66-11e4-8c63-524ab71011b6.png)
Source: http://www.reddit.com/r/elementaryos/comments/360nje/is_there_any_way_i_can_make_the_terminal_stay_on/

**Comment by mank319** [comment] 2015-05-17 10:12
Nice! I'm glad you found a way that works for you :wink: 
I have confirmed that the Gala bug on launchpad affects me too and I will close this issue for now, as indicated earlier :smile:

**Closed by mank319** 2015-05-17 10:12 UTC
