### ISSUE TITLE
Request: It to create a long break duration

### ISSUE THREAD

**Issue by btd1337** [mank319/Go-For-It#126] opened 2018-01-20 16:23 UTC
### Expected behavior
It to create a long break duration function like this.

![screenshot from 2018-01-20 14 19 21](https://user-images.githubusercontent.com/11943860/35185549-80312162-fded-11e7-932f-a16f4d9783fd.jpeg)

**Comment by JMoerman** [comment] 2018-02-06 21:22
This seems to be a duplicate of https://github.com/JMoerman/Go-For-It/issues/34 (https://github.com/mank319/Go-For-It/issues/105).
I'm going to have to change to change the settings dialog anyways as I'm planning to add support for (optionally) having more than one todo list at once. I think this will be included in the next version.

**Closed** 2019-08-31 10:44 UTC

**Comment by JMoerman** [comment] 2019-08-31 10:45
This is possible as of c873a63515dd743854b32c79cfdd58bf95106e44

**Comment by btd1337** [comment] 2019-09-08 04:28
@JMoerman please, could you to change the default value to "long break after" 4 "short breaks"?

It's 4 the default value in the pomodoro technique.

Thanks in advance.

**Comment by JMoerman** [comment] 2019-09-08 08:56
I think you are mistaken: in the picture above you have a long break after 4 pomodoros, while having a long break after 3  long breaks means the following schedule 

- first pomodoro
- first short break
- second pomodoro
- second short break
- third pomodoro
- third short break
- fourth pomodoro
- first long break (4th break)

Otherwise (assuming durations of 25 min and 5 min for the pomodoros and short breaks respectively) the first long break would be after 145 minutes.

**Comment by btd1337** [comment] 2019-09-09 18:12
Oh yes, now I get it.

Is that the technique considers **pomodoros** completed as a reference for the long break. But you considered **short breaks** as a reference. Not wrong, but not common.

To be honest, it's the first app I see that makes it that way.

I tested the functionality and saw some issues:

- After a pomodoro, doesn't start a break and no visual notify is sent to the system.

**Comment by JMoerman** [comment] 2019-09-10 13:57
The reason for my choice of words is that I want users to be able to understand the settings without having heard of the concept of a pomodoro timer. (Right now such a user would still need to be curious enough to select the pomodoro timer mode, but I may change the default at a later date.)


> I tested the functionality and saw some issues:
> 
> * After a pomodoro, doesn't start a break and no visual notify is sent to the system.

Hmm, I'm not able to reproduce this right now.
Let me get this straight: the break timer does not start automatically and no "Take a Break" notification is sent?

Does the reminder notification get sent? What about the notification at the end of the break? Does the timer automatically start after the break (needs to be enabled in the settings)?

**Comment by btd1337** [comment] 2019-09-10 17:52
This is my settings

![Captura de tela de 2019-09-10 14-23-50](https://user-images.githubusercontent.com/11943860/64635730-acf96b80-d3d6-11e9-9c29-836813d2291a.png)


---

Expectancy

0 - Pomodoro: Timer in display = 25 minutes
.
.
.
24- Notification 1 minute left
25 - Notification short break
0 - Short Break: Timer in display = 5 minutes
.
.
.
5 - Notification that break is over
0 - Pomodoro: Timer in display = 25 minutes
.
Repeat the cycle
---

What is going on:

0 - Pomodoro: Timer in display = 25 minutes
.
.
.
25 - Timer is stopped
0 - Pomodoro: Timer in display = 25 minutes
Repeat the cycle

**Comment by JMoerman** [comment] 2019-09-11 10:32
The expected behavior is the only behavior I can reproduce here, no matter what I did.
(Though the timer will stop running after a break if "Resume task after the break is not enabled".)

The only thing I can think of is that somehow the break is 0 seconds long while libnotify also doesn't work properly...

All what I can do at this point is provide you with a more verbose version and look at the command line output for any anomalies, as I cannot fix that which I cannot reproduce.

**Comment by JMoerman** [comment] 2019-10-09 13:04
It has been a while since I have had time to look at this.
I still have not been able to reproduce the issue you describe, but I've made a temporary branch (https://github.com/JMoerman/Go-For-It/tree/debug) that logs some debug info to the command line.
If you have some time available, running this version from the command line may yield some valuable information. (I can also send you a binary if that's more convenient)
